'use strict';
const $=id=>document.getElementById(id);
const token=document.querySelector('meta[name="fly-token"]').content;
const labels={WAIT:'Czekaj',A:'Lewe drzwi',D:'Prawe drzwi',W:'Przedni wentyl',F:'Boczny wentyl',S:'Monitor',SPACE:'Wentylator',Z:'Latarka',X:'Wyłącz systemy',C:'Złap rybę','1':'Generator','2':'Cicha wentylacja','3':'Ogrzewanie','4':'Klimatyzacja','5':'Pozytywka','6':'Wyłącz systemy',ENTER:'Zamknij reklamę',CLICK:'Kliknięcie',MOVE:'Ruch myszy'};
const groupNames={optic:'Płaty wzrokowe',central:'Mózg centralny',visual_projection:'Projekcje wzrokowe',descending:'Zstępujące',ascending:'Wstępujące',sensory:'Sensoryczne',sensory_ascending:'Sensoryczno-wstępujące',visual_centrifugal:'Wzrokowe odśrodkowe',motor:'Ruchowe',endocrine:'Endokrynne',unknown:'Bez klasyfikacji'};
const modes={pause:'PAUZA',watch:'OBSERWACJA',teach:'NAUKA Z GRACZA',play:'MODEL GRA',explore:'TRENING Z NAGRODĄ'};
let anatomy=null,state=null,selected=-1,filter=-1,yaw=.18,pitch=-.08,zoom=1,autoRotate=false,showEdges=false,lastTick=-1;
let activity=[],projected=[],drag=null,moved=false;
const canvas=$('brain'),ctx=canvas.getContext('2d');
async function command(command,extra={}){try{const response=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json','X-Fly-Token':token},body:JSON.stringify({command,...extra})});if(!response.ok)throw Error('Błąd komendy');}catch(e){$('note').textContent='Brak połączenia z programem. '+e.message;}}
document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>command(b.dataset.command));
document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>command('template',{kind:b.dataset.template}));
$('mouse').onchange=e=>command('mouse',{enabled:e.target.checked});
$('resetView').onclick=()=>{yaw=.18;pitch=-.08;zoom=1;filter=-1;selected=-1;};
$('rotate').onclick=()=>{$('rotate').setAttribute('aria-pressed',String(autoRotate=!autoRotate));};
$('edgeToggle').onclick=()=>{$('edgeToggle').setAttribute('aria-pressed',String(showEdges=!showEdges));};
$('clearFilter').onclick=()=>{filter=-1;updateRegions();};
$('stimulate').onclick=()=>{if(filter<0){$('note').textContent='Najpierw wybierz obszar poniżej modelu.';return;}command('stimulate',{group:filter});};
$('clearStim').onclick=()=>command('stimulate',{group:null});
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY,yaw,pitch];moved=false;canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.abs(dx)+Math.abs(dy)>4)moved=true;yaw=drag[2]+dx*.006;pitch=Math.max(-1.5,Math.min(1.5,drag[3]+dy*.006));};
canvas.onpointerup=e=>{if(!moved){const r=canvas.getBoundingClientRect();let best=12,index=-1;projected.forEach((p,i)=>{if(!p||!p.visible)return;const d=Math.hypot(p.x-(e.clientX-r.left),p.y-(e.clientY-r.top));if(d<best){best=d;index=i;}});selected=index;updateDetail();}drag=null;};
canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.45,Math.min(3.5,zoom*Math.exp(-e.deltaY*.001)));};
function updateDetail(){const box=$('neuronDetail');box.replaceChildren();const label=document.createElement('span');label.className='eyebrow';label.textContent=selected<0?'WYBIERZ NEURON':'NEURON FLYWIRE';box.append(label);if(selected<0){const p=document.createElement('p');p.textContent='Kliknij punkt, aby zobaczyć identyfikator i aktywność.';box.append(p);return;}const id=document.createElement('strong');id.textContent=anatomy.ids[selected];box.append(id);const p=document.createElement('p');const g=anatomy.labels[anatomy.groups[selected]];p.textContent=(anatomy.types[selected]||groupNames[g]||g)+' · '+anatomy.nt[selected];box.append(p);const v=document.createElement('p');v.textContent='Aktywność: '+Number(activity[selected]||0).toFixed(4);box.append(v);}
function updateRegions(){if(!anatomy)return;anatomy.labels.forEach((g,i)=>{const b=$('region-'+i);b.classList.toggle('active',filter===i);const value=state?.groups[i]||0;b.querySelector('span:last-of-type').textContent=value.toFixed(3);b.querySelector('i').style.width=Math.min(100,value*250)+'%';});}
function render(t){requestAnimationFrame(render);if(!anatomy)return;const r=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(r.width*dpr)||canvas.height!==Math.round(r.height*dpr)){canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);if(autoRotate&&!drag)yaw+=.002;const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),scale=Math.min(r.width*.38,r.height*.70)*zoom;
  // Subtle reference grid; all neuron positions come from the downloaded anatomy.
  ctx.strokeStyle='#213b4338';ctx.lineWidth=.5;for(let i=-3;i<=3;i++){ctx.beginPath();ctx.moveTo(r.width*.5+i*scale*.25,r.height*.15);ctx.lineTo(r.width*.5+i*scale*.25,r.height*.86);ctx.stroke();}
  projected=anatomy.xyz.map((v,i)=>{const x=v[0]*cy+v[2]*sy,z=-v[0]*sy+v[2]*cy,y=v[1]*cp-z*sp,z2=v[1]*sp+z*cp,perspective=3.8/(3.8-z2*.25);return{x:r.width*.5+x*scale*perspective,y:r.height*.48+y*scale*perspective,z:z2,visible:filter<0||anatomy.groups[i]===filter};});
  if(showEdges){ctx.lineWidth=.45;for(const [a,b]of anatomy.edges){const p=projected[a],q=projected[b];if(!p.visible||!q.visible)continue;const energy=Math.max(Math.abs(activity[a]||0),Math.abs(activity[b]||0));ctx.strokeStyle=`rgba(103,215,195,${.035+energy*.32})`;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}
  const order=Array.from({length:projected.length},(_,i)=>i).sort((a,b)=>projected[a].z-projected[b].z);
  for(const i of order){const p=projected[i],v=activity[i]||0,a=Math.min(1,Math.abs(v)*1.6);let alpha=p.visible?.26+a*.74:.035;ctx.fillStyle=v<-.015?`rgba(${Math.round(104+a*36)},${Math.round(151+a*32)},255,${alpha})`:`rgba(${Math.round(71+a*74)},${Math.round(142+a*110)},${Math.round(157+a*56)},${alpha})`;ctx.beginPath();ctx.arc(p.x,p.y,p.visible?1+a*1.5:.6,0,Math.PI*2);ctx.fill();if(i===selected){ctx.strokeStyle='#ffffff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.stroke();}}
}
function history(items){const el=$('history');el.replaceChildren();if(!items.length){el.textContent='Oczekiwanie na pierwsze zdarzenie.';return;}for(const item of items){const d=document.createElement('div'),time=document.createElement('time'),p=document.createElement('p');time.textContent=item.time;p.textContent=item.message;d.append(time,p);el.append(d);}}
async function poll(){try{const response=await fetch('/api/state');if(!response.ok)throw Error();state=await response.json();activity=state.activity;$('mode').textContent=modes[state.mode]||state.mode;$('connection').textContent=state.offline?'TEST SYNTETYCZNY — bez gry':state.focused?'UCN aktywne · połączenie lokalne':state.connected?'UCN w tle · wejście wstrzymane':'Oczekiwanie na aktywne UCN';$('led').classList.toggle('on',state.focused&&state.mode!=='pause');$('fps').textContent=state.focused&&state.mode!=='pause'?state.fps.toFixed(1):'0.0';$('note').textContent=state.note;$('action').textContent=labels[state.action]||state.action;$('confidence').textContent=Math.round(Math.max(...state.probabilities)*100)+'%';$('samples').textContent=state.samples.toLocaleString('pl');$('updates').textContent=state.updates.toLocaleString('pl');$('loss').textContent=state.updates?state.loss.toFixed(3):'—';$('reward').textContent=state.reward.toFixed(1);$('mouse').checked=state.mouse;
    const active=state.counts.slice(1).reduce((a,b)=>a+b,0),total=state.counts.reduce((a,b)=>a+b,0);$('progress').style.width=Math.min(100,100*Math.min(total/200,active/30,state.updates/50))+'%';$('ready').textContent=state.ready?'GOTOWY DO PRÓBY':state.samples?'ZBIERANIE PRZYKŁADÓW':'BRAK DEMONSTRACJI';$('trainingHint').textContent=state.ready?`Zapisano ${total} przykładów, w tym ${active} akcji. Możesz wykonać próbę F7. Gotowość oznacza ilość danych, nie potwierdzoną skuteczność w grze.`:`Zebrano ${total}/200 próbek i ${active}/30 akcji. W UCN naciśnij F6 i pokaż kilka rozgrywek. Sieć uczy się Twoich decyzji.`;
    const bars=$('actions');bars.replaceChildren();state.probabilities.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p).slice(0,4).forEach(({p,i})=>{const row=document.createElement('div');row.className='action-bar';const name=document.createElement('span'),track=document.createElement('div'),fill=document.createElement('i'),value=document.createElement('span');name.textContent=labels[state.actions[i]];track.className='track';fill.style.width=(p*100)+'%';value.textContent=Math.round(p*100)+'%';track.append(fill);row.append(name,track,value);bars.append(row);});
    if(state.frame_time){const age=Math.max(0,Date.now()/1000-state.frame_time);$('frameStatus').textContent=age<1?'AKTUALNY OBRAZ':'OSTATNIA KLATKA';$('frameAge').textContent=age<1?'UCN · na żywo':`zapis sprzed ${Math.round(age)} s`;if(state.ticks!==lastTick){$('gameFrame').src='/api/frame?t='+state.ticks;$('gameFrame').hidden=false;$('framePlaceholder').hidden=true;lastTick=state.ticks;}}
    $('templates').textContent=state.templates.length?'Zapisane wzorce: '+state.templates.join(', '):'Brak wzorców — koniec nocy oznacz ręcznie.';history(state.history);updateRegions();if(selected>=0)updateDetail();document.querySelectorAll('[data-command]').forEach(b=>b.classList.toggle('active',b.dataset.command===state.mode));
  }catch(e){$('connection').textContent='Program jest rozłączony';$('led').classList.remove('on');$('note').textContent='Uruchom START_FLY.bat w folderze projektu, potem odśwież tę stronę.';}finally{setTimeout(poll,180);}}
async function init(){try{const response=await fetch('/api/anatomy');if(!response.ok)throw Error('Nie udało się pobrać anatomii');anatomy=await response.json();$('neurons').textContent=anatomy.metadata.neurons.toLocaleString('pl');$('edges').textContent=(anatomy.metadata.edges/1e6).toFixed(1)+' mln';$('shown').textContent=`${anatomy.ids.length.toLocaleString('pl')} neuronów w widoku · pełna sieć w symulacji`;
    anatomy.labels.forEach((g,i)=>{const b=document.createElement('button');b.id='region-'+i;b.className='region';const name=document.createElement('span'),value=document.createElement('span'),bar=document.createElement('i');name.textContent=groupNames[g]||g;value.textContent='0.000';b.append(name,value,bar);b.onclick=()=>{filter=filter===i?-1:i;updateRegions();};$('regions').append(b);});requestAnimationFrame(render);poll();}catch(e){$('note').textContent=e.message;}}
init();
