'use strict';
let defenseCatalog=[];
setInterval(()=>{if(!state?.audio)return;const a=state.audio;document.getElementById('audioStatus').textContent=a.status+' · pakiety analizy: '+a.packets+(a.error?' · '+a.error.slice(0,160):'');document.getElementById('audioLeft').value=a.left;document.getElementById('audioRight').value=a.right;},500);
function showDefense(){const row=defenseCatalog[Number(document.getElementById('enemy').value)];if(!row)return;document.getElementById('enemyDescription').textContent=row.description;document.getElementById('enemySignal').textContent='Potrzebny sygnał: '+row.signal;document.getElementById('enemyCoverage').textContent=row.automated.length?'Częściowe wsparcie automatyczne: '+row.automated.map(k=>({cool:'chłodzenie',music:'globalna pozytywka',mute_call:'wyciszenie rozmowy',dismiss_ad:'zamknięcie reklamy'}[k]||k)).join(', ')+'. '+row.limitation:'Opis dostępny. '+row.limitation;document.getElementById('enemySource').href=row.source;}
fetch('/api/knowledge').then(r=>{if(!r.ok)throw Error();return r.json();}).then(rows=>{defenseCatalog=rows;const box=document.getElementById('enemy');rows.forEach((row,i)=>{let o=document.createElement('option');o.value=i;o.textContent=row.name;box.append(o);});box.onchange=showDefense;showDefense();}).catch(()=>{document.getElementById('enemyDescription').textContent='Uruchom ponownie program, aby wczytać bazę obrony.';});
setInterval(()=>{if(!state)return;document.getElementById('continuous').textContent=(state.training_health||'')+' · Ostatnia zmiana wag: '+(state.last_weight_change?new Date(state.last_weight_change*1000).toLocaleTimeString():'jeszcze brak')+' · Wielkość zmiany: '+Number(state.last_update_delta||0).toFixed(6)+' · Aktualizacje w trakcie nocy: '+(state.continuous_updates||0)+' · akcje z reguł obrony: '+(state.guided_steps||0)+' · oczekujące próbki: '+(state.pending_steps||0);document.getElementById('defenseReason').textContent=state.defense_reason||'Brak potwierdzonego sygnału obrony';},750);
const $=id=>document.getElementById(id),token=document.querySelector('[name="fly-token"]').content;
if(document.querySelector('[name="control"]').content!=='true')document.body.classList.add('viewer');
document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=async()=>{try{let r=await fetch('/api/command',{method:'POST',headers:{'Content-Type':'application/json','X-Fly-Token':token},body:JSON.stringify({command:b.dataset.cmd})});if(!r.ok)throw Error(r.status);$('note').textContent='Polecenie przyjęte. Po wznowieniu przełącz się do UCN.';}catch(e){$('note').textContent='Nie udało się wysłać polecenia: '+e.message;}});
let anatomy=null,state=null,angle=.2,pitch=0,zoom=1,rotating=false,showEdges=false,filter=-1,selected=-1,points=[],drag=null,lastTick=-1;
const canvas=$('brain'),ctx=canvas.getContext('2d');
$('rotate').onclick=()=>rotating=!rotating;$('edges').onclick=()=>showEdges=!showEdges;
$('zoomIn').onclick=()=>zoom=Math.min(3,zoom*1.2);$('zoomOut').onclick=()=>zoom=Math.max(.4,zoom/1.2);
$('region').onchange=e=>filter=Number(e.target.value);
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,angle,pitch,moved:false};canvas.setPointerCapture(e.pointerId);};
canvas.onpointermove=e=>{if(!drag)return;let x=e.clientX-drag.x,y=e.clientY-drag.y;if(Math.hypot(x,y)>4)drag.moved=true;angle=drag.angle+x*.008;pitch=Math.max(-1.5,Math.min(1.5,drag.pitch+y*.008));};
canvas.onpointerup=e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect();let d=15;selected=-1;points.forEach((p,i)=>{let v=Math.hypot(p.x-e.clientX+r.left,p.y-e.clientY+r.top);if(p.visible&&v<d){selected=i;d=v;}});}drag=null;};
canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.4,Math.min(3,zoom*Math.exp(-e.deltaY*.001)));};
function sized(c){let r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(r.width*d)||c.height!==Math.round(r.height*d)){c.width=Math.round(r.width*d);c.height=Math.round(r.height*d);}let x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);return[r,x];}
function draw(){requestAnimationFrame(draw);if(!anatomy)return;let [r,c]=sized(canvas);if(rotating&&!drag)angle+=.002;let co=Math.cos(angle),si=Math.sin(angle),cp=Math.cos(pitch),sp=Math.sin(pitch),scale=Math.min(r.width*.38,r.height*.7)*zoom;
points=anatomy.xyz.map((v,i)=>{let x=v[0]*co+v[2]*si,z=-v[0]*si+v[2]*co;return{x:r.width/2+x*scale,y:r.height/2+(v[1]*cp-z*sp)*scale,visible:filter<0||anatomy.groups[i]===filter};});
if(showEdges){c.strokeStyle='#72d9b52d';c.lineWidth=.6;for(const[a,b]of anatomy.edges){let p=points[a],q=points[b];if(!p.visible||!q.visible)continue;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke();}}
points.forEach((p,i)=>{if(!p.visible)return;let v=state?.activity[i]||0,a=Math.min(1,Math.abs(v)*2);c.fillStyle=v<0?`rgba(112,161,255,${.2+a*.8})`:`rgba(109,242,191,${.2+a*.8})`;c.beginPath();c.arc(p.x,p.y,1+a*1.5,0,Math.PI*2);c.fill();if(i===selected){c.strokeStyle='#fff';c.beginPath();c.arc(p.x,p.y,7,0,Math.PI*2);c.stroke();}});
if(selected>=0)$('neuron').textContent=`FlyWire ${anatomy.ids[selected]} · ${anatomy.types[selected]||anatomy.labels[anatomy.groups[selected]]} · aktywność ${(state?.activity[selected]||0).toFixed(4)}`;
}
function chart(results){let[r,c]=sized($('chart'));if(!results.length){c.fillStyle='#8fa9b0';c.fillText('Wykres pojawi się po pierwszej zakończonej nocy.',10,80);return;}let max=Math.max(10,...results.map(v=>v.seconds));c.strokeStyle='#7be0b7';c.lineWidth=2;c.beginPath();results.forEach((v,i)=>{let x=20+i*(r.width-40)/Math.max(1,results.length-1),y=r.height-25-v.seconds/max*(r.height-50);i?c.lineTo(x,y):c.moveTo(x,y);c.fillStyle=v.result==='win'?'#fff':'#7be0b7';c.fillRect(x-3,y-3,6,6);});c.stroke();c.fillStyle='#8fa9b0';c.fillText(`${max.toFixed(1)} s`,5,14);c.fillText(`Próby ${results[0].episode}–${results.at(-1).episode}`,10,r.height-5);}
async function poll(){try{let r=await fetch('/api/state');if(!r.ok)throw Error(r.status);state=await r.json();$('status').textContent=state.paused?'ZATRZYMANO':state.focused?'UCN aktywne · '+state.fps+' kl./s':'Czekam na aktywne UCN';$('note').textContent=state.note;$('phase').textContent=state.phase;$('action').textContent=state.action;$('difficulty').textContent=state.verified50?'· potwierdzone 50/20':'';for(let k of ['episodes','updates','wins'])$(k).textContent=state[k];for(let k of ['seconds','best'])$(k).textContent=state[k].toFixed(1)+' s';$('learning').textContent=`Decyzje: ${state.steps} · błąd wartości: ${state.loss.toFixed(3)} · entropia: ${state.entropy.toFixed(2)}`;if(state.ticks!==lastTick){$('frame').src='/api/frame?t='+state.ticks;lastTick=state.ticks;}$('age').textContent=state.frame_time?`Klatka sprzed ${Math.max(0,Date.now()/1000-state.frame_time).toFixed(1)} s`:'Oczekiwanie na grę';$('events').replaceChildren(...state.history.map(v=>{let p=document.createElement('p');p.textContent=`${v.time} · ${v.event} · ${v.reason||v.result||v.difficulty||''}${v.seconds!==undefined?' · '+v.seconds+' s':''}`;return p;}));$('ocr').textContent=state.ocr.join(' | ');if(state.phone_urls){$('links').replaceChildren(...state.phone_urls.map(url=>{let a=document.createElement('a');a.href=url;a.textContent=url;return a;}));}chart(state.results);}catch(e){$('status').textContent='Brak połączenia';$('note').textContent='Uruchom START_FLY.bat na komputerze.';}finally{setTimeout(poll,450);}}
fetch('/api/anatomy').then(r=>r.json()).then(a=>{anatomy=a;$('anatomy').textContent=`${a.metadata.neurons.toLocaleString('pl')} neuronów · ${(a.metadata.edges/1e6).toFixed(1)} mln połączeń · ${a.ids.length} punktów w widoku 3D`;a.labels.forEach((g,i)=>{let o=document.createElement('option');o.value=i;o.textContent=g;$('region').append(o);});draw();}).catch(()=>{$('anatomy').textContent='Nie udało się pobrać anatomii. Odśwież stronę.';});poll();
